[package]
name = "rascii"
version = "1.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
image = "0.25"
rusttype = "0.9"
termion = "2.0"
log = "0.4"
env_logger = "0.11"
colored = "2"
figlet-rs = "0.1.5"
opencv = "0.95.0"
rayon = "1.10.0"
